In [1]:
import numpy as np
arr= np.random.randint(low=0,high=20, size=11)

In [41]:
print(*arr)

0 10 10 9 7 10 17 8 0 8 6


## Idea:

selection sort, Takes  Smallest number and place it in it's right position.<br>
it will start by taking initial value and  will compare the entire array with it.<br> 
If any smaller value is found then it will swap it with the considered value<br>

In [5]:
def selection_sort(arr):
    N= len(arr)
    for i in range(N):
        minimum= i
        for j in range(i+1,N):
            if arr[minimum] > arr[j]:
                minimum = j
        temp= arr[i]
        arr[i]= arr[minimum]
        arr[minimum]= temp
        print(*arr)
    return arr
        
print('Starting array :',*arr,'\n\n')
a1= selection_sort(arr.copy())
print('\n\nFinal array:',*a1)

Starting array : 10 10 14 7 9 19 10 0 2 18 11 


0 10 14 7 9 19 10 10 2 18 11
0 2 14 7 9 19 10 10 10 18 11
0 2 7 14 9 19 10 10 10 18 11
0 2 7 9 14 19 10 10 10 18 11
0 2 7 9 10 19 14 10 10 18 11
0 2 7 9 10 10 14 19 10 18 11
0 2 7 9 10 10 10 19 14 18 11
0 2 7 9 10 10 10 11 14 18 19
0 2 7 9 10 10 10 11 14 18 19
0 2 7 9 10 10 10 11 14 18 19
0 2 7 9 10 10 10 11 14 18 19


Final array: 0 2 7 9 10 10 10 11 14 18 19


    Time complexity
    +-------+----------+----------+
    | Best  |  Average |  Worst   |
    +-------+----------+----------+
    | O(n²) |   O(n²)  |   O(n²)  |
    +-------+----------+----------+

## 

## 

## Bubble sort

## Idea:
Bubble sort came from idea of " Bubbles ", where bigger bubble tends to come out first from water.
This algo compares two elements at a time and sort the two elements by keeping smaller one at left and bigger one at right and thus repeating again and again.

In [6]:
arr

array([10, 10, 14,  7,  9, 19, 10,  0,  2, 18, 11])

In [7]:
def bubble_sort(arr):
    N= len(arr)
    for j in range(N-1):
        for i in range(N-1):
            if arr[i] <= arr[i+1]:
                continue
            else:
                temp= arr[i+1]
                arr[i+1]= arr[i]
                arr[i]= temp
        print(*arr)
    print('\n\nfinal array:',*arr)
print("Starting array :",*arr,'\n\n')
bubble_sort(arr.copy())


Starting array : 10 10 14 7 9 19 10 0 2 18 11 


10 10 7 9 14 10 0 2 18 11 19
10 7 9 10 10 0 2 14 11 18 19
7 9 10 10 0 2 10 11 14 18 19
7 9 10 0 2 10 10 11 14 18 19
7 9 0 2 10 10 10 11 14 18 19
7 0 2 9 10 10 10 11 14 18 19
0 2 7 9 10 10 10 11 14 18 19
0 2 7 9 10 10 10 11 14 18 19
0 2 7 9 10 10 10 11 14 18 19
0 2 7 9 10 10 10 11 14 18 19


final array: 0 2 7 9 10 10 10 11 14 18 19


    Time complexity
    +------+----------+----------+
    | Best |  Average |  Worst   |
    +------+----------+----------+
    | O(n) |   O(n²)  |   O(n²)  |
    +------+----------+----------+


## Merge sort

In [25]:
def merge(left,right):
    i=0
    j=0
    li=[]
    while True:
        if left[i]<=right[j]:
            li.append(left[i])
            i+=1
        else:
            li.append(right[j])
            j+=1
        if i == len(left) or j== len(right):
            break
    if i <len(left):
        for x in range(i,len(left)):
            li.append(left[x])
    if j < len(right):
        for x in range(j, len(right)):
            li.append(right[x])
    return li
merge([0,1],[1,7])

[0, 1, 1, 7]

In [26]:
def merge_sort(arr):
    if len(arr)==1:
        return arr
    mid= len(arr)//2
    left= arr[:mid]
    right= arr[mid:]
    a= merge_sort(left)
    b= merge_sort(right)
    return merge(a,b)
merge_sort(arr)


[1, 3, 4, 4, 9, 9, 11, 11, 15, 16, 19]

## Insertion  Sort

## Idea: (CARDS)
```logic 1 but 3 phases:
    j hoga second element
    i hoga j-1
    or key hoga jth element {copy karne ke baad element overrite na hojaye}<br>
    
    i minus 1 hota rahega, jab tak list khatam na ho
    j sirf key element decide ke liye hai
    
    if A[i]>0 and A[i]>key:
    A[i+1]= A[i] {copy karlo element ko uske agey waley cell me } 
    i-=1 {baki element se compare karne ke liye, i piche piche jata rahega}

A[i+1]= key {jab i = -1 toh jo element bacha hoga usko 0th location mai save karne ke liye AUR jab A[i] element key se chota hoga toh badey element ko i+1 location mai store karne ke liye} 

```

In [4]:
arr

array([ 8,  3,  3, 16, 18, 18, 17, 15,  3, 11, 13])

In [8]:
def insertion_sort(arr):
    N= len(arr)
    for j in range(1, N):
        key= arr[j]
        i=j-1
        while(i>-1 and arr[i]>key):
            arr[i+1]= arr[i]
            i-=1
        arr[i+1]= key
    return arr
insertion_sort(arr.copy())

array([ 3,  3,  3,  8, 11, 13, 15, 16, 17, 18, 18])

## Quick sort

In [2]:
#not working
def partition(A,p,r):
    i=p-1
    x= A[r]
    for j in range(p,r):
        if A[j]<x:
            i+=1
            temp= A[i]
            A[i]= A[j]
            A[j]=temp
    temp= A[j]
    A[j]= A[i+1]
    A[i+1]=temp
    return i+1
def quick_sort(A,p,r):
    print(A)
    if p<r:
        q= partition(A,p,r)
        print(q)
        quick_sort(A,p,q)
        quick_sort(A,q+1,r)
        
f= [7,4,1,3,0,6]
# partition(f, 0, len(f)-1)
quick_sort(f,0,len(f)-1)

[7, 4, 1, 3, 0, 6]
4
[4, 1, 3, 0, 7, 6]
4
[4, 1, 3, 7, 0, 6]
0
[7, 1, 3, 4, 0, 6]
[7, 1, 3, 4, 0, 6]
1
[7, 4, 3, 1, 0, 6]
[7, 4, 3, 1, 0, 6]
2
[7, 4, 1, 3, 0, 6]
[7, 4, 1, 3, 0, 6]
3
[7, 4, 1, 3, 0, 6]
[7, 4, 1, 3, 0, 6]
[7, 4, 1, 3, 0, 6]
[7, 4, 1, 3, 0, 6]


In [47]:
sorted(f)

[0, 1, 3, 4, 6, 7]

In [3]:
  f

[7, 4, 1, 3, 0, 6]